# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.5.5
group=derekahedron.invexp
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Inventory Expansion
mod_author=Derekahedron
mod_id=invexp
license=MIT
credits=
description=Adds items that help manage your inventory. Automatically pick up items into sacks and quivers which can store multiple stacks in one item.
minecraft_version_range=[1.20.1]
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.3.22
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Compat Mod
compat_mod_id=invexpcompat
compat_version=1.0.3
